/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrganizationRouteImport } from './routes/dashboard/organization'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/dashboard/projects/$projectId/index'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard/projects/$projectId/settings'
import { Route as DashboardProjectsProjectIdSessionsRouteImport } from './routes/dashboard/projects/$projectId/sessions'
import { Route as DashboardProjectsProjectIdRetentionRouteImport } from './routes/dashboard/projects/$projectId/retention'
import { Route as DashboardProjectsProjectIdPlayersRouteImport } from './routes/dashboard/projects/$projectId/players'
import { Route as DashboardProjectsProjectIdOverviewRouteImport } from './routes/dashboard/projects/$projectId/overview'
import { Route as DashboardProjectsProjectIdMapsRouteImport } from './routes/dashboard/projects/$projectId/maps'
import { Route as DashboardProjectsProjectIdLiveRouteImport } from './routes/dashboard/projects/$projectId/live'
import { Route as DashboardProjectsProjectIdFunnelsRouteImport } from './routes/dashboard/projects/$projectId/funnels'
import { Route as DashboardProjectsProjectIdEventsRouteImport } from './routes/dashboard/projects/$projectId/events'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationRoute = DashboardOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSessionsRoute =
  DashboardProjectsProjectIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdRetentionRoute =
  DashboardProjectsProjectIdRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdPlayersRoute =
  DashboardProjectsProjectIdPlayersRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdOverviewRoute =
  DashboardProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdMapsRoute =
  DashboardProjectsProjectIdMapsRouteImport.update({
    id: '/maps',
    path: '/maps',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdLiveRoute =
  DashboardProjectsProjectIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdFunnelsRoute =
  DashboardProjectsProjectIdFunnelsRouteImport.update({
    id: '/funnels',
    path: '/funnels',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEventsRoute =
  DashboardProjectsProjectIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/funnels': typeof DashboardProjectsProjectIdFunnelsRoute
  '/dashboard/projects/$projectId/live': typeof DashboardProjectsProjectIdLiveRoute
  '/dashboard/projects/$projectId/maps': typeof DashboardProjectsProjectIdMapsRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/players': typeof DashboardProjectsProjectIdPlayersRoute
  '/dashboard/projects/$projectId/retention': typeof DashboardProjectsProjectIdRetentionRoute
  '/dashboard/projects/$projectId/sessions': typeof DashboardProjectsProjectIdSessionsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/funnels': typeof DashboardProjectsProjectIdFunnelsRoute
  '/dashboard/projects/$projectId/live': typeof DashboardProjectsProjectIdLiveRoute
  '/dashboard/projects/$projectId/maps': typeof DashboardProjectsProjectIdMapsRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/players': typeof DashboardProjectsProjectIdPlayersRoute
  '/dashboard/projects/$projectId/retention': typeof DashboardProjectsProjectIdRetentionRoute
  '/dashboard/projects/$projectId/sessions': typeof DashboardProjectsProjectIdSessionsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/funnels': typeof DashboardProjectsProjectIdFunnelsRoute
  '/dashboard/projects/$projectId/live': typeof DashboardProjectsProjectIdLiveRoute
  '/dashboard/projects/$projectId/maps': typeof DashboardProjectsProjectIdMapsRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/players': typeof DashboardProjectsProjectIdPlayersRoute
  '/dashboard/projects/$projectId/retention': typeof DashboardProjectsProjectIdRetentionRoute
  '/dashboard/projects/$projectId/sessions': typeof DashboardProjectsProjectIdSessionsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/funnels'
    | '/dashboard/projects/$projectId/live'
    | '/dashboard/projects/$projectId/maps'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/players'
    | '/dashboard/projects/$projectId/retention'
    | '/dashboard/projects/$projectId/sessions'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/projects'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/funnels'
    | '/dashboard/projects/$projectId/live'
    | '/dashboard/projects/$projectId/maps'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/players'
    | '/dashboard/projects/$projectId/retention'
    | '/dashboard/projects/$projectId/sessions'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/funnels'
    | '/dashboard/projects/$projectId/live'
    | '/dashboard/projects/$projectId/maps'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/players'
    | '/dashboard/projects/$projectId/retention'
    | '/dashboard/projects/$projectId/sessions'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organization': {
      id: '/dashboard/organization'
      path: '/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof DashboardOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/sessions': {
      id: '/dashboard/projects/$projectId/sessions'
      path: '/sessions'
      fullPath: '/dashboard/projects/$projectId/sessions'
      preLoaderRoute: typeof DashboardProjectsProjectIdSessionsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/retention': {
      id: '/dashboard/projects/$projectId/retention'
      path: '/retention'
      fullPath: '/dashboard/projects/$projectId/retention'
      preLoaderRoute: typeof DashboardProjectsProjectIdRetentionRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/players': {
      id: '/dashboard/projects/$projectId/players'
      path: '/players'
      fullPath: '/dashboard/projects/$projectId/players'
      preLoaderRoute: typeof DashboardProjectsProjectIdPlayersRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/overview': {
      id: '/dashboard/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/dashboard/projects/$projectId/overview'
      preLoaderRoute: typeof DashboardProjectsProjectIdOverviewRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/maps': {
      id: '/dashboard/projects/$projectId/maps'
      path: '/maps'
      fullPath: '/dashboard/projects/$projectId/maps'
      preLoaderRoute: typeof DashboardProjectsProjectIdMapsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/live': {
      id: '/dashboard/projects/$projectId/live'
      path: '/live'
      fullPath: '/dashboard/projects/$projectId/live'
      preLoaderRoute: typeof DashboardProjectsProjectIdLiveRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/funnels': {
      id: '/dashboard/projects/$projectId/funnels'
      path: '/funnels'
      fullPath: '/dashboard/projects/$projectId/funnels'
      preLoaderRoute: typeof DashboardProjectsProjectIdFunnelsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/events': {
      id: '/dashboard/projects/$projectId/events'
      path: '/events'
      fullPath: '/dashboard/projects/$projectId/events'
      preLoaderRoute: typeof DashboardProjectsProjectIdEventsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdEventsRoute: typeof DashboardProjectsProjectIdEventsRoute
  DashboardProjectsProjectIdFunnelsRoute: typeof DashboardProjectsProjectIdFunnelsRoute
  DashboardProjectsProjectIdLiveRoute: typeof DashboardProjectsProjectIdLiveRoute
  DashboardProjectsProjectIdMapsRoute: typeof DashboardProjectsProjectIdMapsRoute
  DashboardProjectsProjectIdOverviewRoute: typeof DashboardProjectsProjectIdOverviewRoute
  DashboardProjectsProjectIdPlayersRoute: typeof DashboardProjectsProjectIdPlayersRoute
  DashboardProjectsProjectIdRetentionRoute: typeof DashboardProjectsProjectIdRetentionRoute
  DashboardProjectsProjectIdSessionsRoute: typeof DashboardProjectsProjectIdSessionsRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdEventsRoute:
      DashboardProjectsProjectIdEventsRoute,
    DashboardProjectsProjectIdFunnelsRoute:
      DashboardProjectsProjectIdFunnelsRoute,
    DashboardProjectsProjectIdLiveRoute: DashboardProjectsProjectIdLiveRoute,
    DashboardProjectsProjectIdMapsRoute: DashboardProjectsProjectIdMapsRoute,
    DashboardProjectsProjectIdOverviewRoute:
      DashboardProjectsProjectIdOverviewRoute,
    DashboardProjectsProjectIdPlayersRoute:
      DashboardProjectsProjectIdPlayersRoute,
    DashboardProjectsProjectIdRetentionRoute:
      DashboardProjectsProjectIdRetentionRoute,
    DashboardProjectsProjectIdSessionsRoute:
      DashboardProjectsProjectIdSessionsRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardOrganizationRoute: typeof DashboardOrganizationRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrganizationRoute: DashboardOrganizationRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
